services:

  postgres:
    image: postgres:18-alpine
    environment:
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_USER=fastapi
      - POSTGRES_DB=fastapi

  fastapi:
    build: .
    depends_on:
      - postgres
    env_file:
      - .env.docker
